// Locally hosted city artwork keeps the city heroes reliable and avoids
// depending on external image redirects at runtime.
export const CITY_HERO_IMAGES: Record<string, string> = {
  London: '/city-heroes/london.png',
  Manchester: '/city-heroes/manchester.png',
  Birmingham: '/city-heroes/birmingham.png',
  Glasgow: '/city-heroes/glasgow.png',
  Edinburgh: '/city-heroes/edinburgh.png',
  Leeds: '/city-heroes/leeds.png',
  Liverpool: '/city-heroes/liverpool.png',
  Bristol: '/city-heroes/bristol.png',
  Cardiff: '/city-heroes/cardiff.png',
  Belfast: '/city-heroes/belfast.png',
  Nottingham: '/city-heroes/nottingham.png',
  Newcastle: '/city-heroes/newcastle.png',
  Leicester: '/city-heroes/leicester.png',
  Sheffield: '/city-heroes/sheffield.png',
  Derby: '/city-heroes/derby.png',
  Coventry: '/city-heroes/coventry.png',
  Southampton: '/city-heroes/southampton.png',
  Portsmouth: '/city-heroes/portsmouth.png',
  Norwich: '/city-heroes/norwich.png',
  Brighton: '/city-heroes/brighton.png',
  Oxford: '/city-heroes/oxford.png',
  Cambridge: '/city-heroes/cambridge.png',
  Exeter: '/city-heroes/exeter.png',
  Plymouth: '/city-heroes/plymouth.png',
  Hull: '/city-heroes/hull.png',
  Middlesbrough: '/city-heroes/middlesbrough.png',
  Sunderland: '/city-heroes/sunderland.png',
  Bradford: '/city-heroes/bradford.png',
  Reading: '/city-heroes/reading.png',
  'Milton Keynes': '/city-heroes/milton-keynes.png',
  Bournemouth: '/city-heroes/bournemouth.png',
  Ipswich: '/city-heroes/ipswich.png',
  'Stoke-on-Trent': '/city-heroes/stoke-on-trent.png',
  Wolverhampton: '/city-heroes/wolverhampton.png',
  Swansea: '/city-heroes/swansea.png',
  Aberdeen: '/city-heroes/aberdeen.png',
}
