// Short, genuinely-researched narrative intros for city pages — the "thin
// content" gap flagged in the 2026-09-25 monetization notes: city pages
// were pure database listings with zero descriptive text about the city
// itself, which both reads thin to visitors and gives search engines
// nothing but boilerplate to differentiate one city page from another for
// queries like "concerts in <city>".
//
// Each entry must be based on real, checked facts (venue names, capacities,
// what they're known for) — never invented. Only add a city here once it's
// been properly researched; a city with no entry here just doesn't render
// the "About {city}'s live scene" section, which is fine and expected.
//
// Written 2026-09-29 (Derby pilot), all remaining 35 cities researched and
// added 2026-09-30 — see claude/local-hub-pilot-2026-09-29.md in the
// project for the wider local content push this belongs to. Every fact
// below traces to a verifiable source (Wikipedia, official venue pages,
// or established press) gathered via research agents that same day.
export const CITY_GUIDE_INTROS: Record<string, string> = {
  London: `London's live scene is the country's biggest, anchored by The O2 Arena, one of the world's busiest music arenas since it opened in 2007, and Wembley Stadium, the UK's largest stadium and home to Coldplay's record-breaking run of shows. OVO Arena Wembley, in the same building since 1934, has hosted everyone from The Beatles to Queen. For something smaller, Camden's Roundhouse — a converted Victorian railway shed — and Brixton's O2 Academy, the Art Deco venue where The Smiths played their final gig, both carry real music history, while the West End's London Palladium remains a home of British variety theatre. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Manchester: `Manchester's music heritage runs deep — the "Madchester" scene of the late 1980s grew out of The Haçienda, and bands like Oasis and The Smiths remain closely tied to the city. Today it's home to two major arenas: Co-op Live, the UK's largest indoor arena, and the AO Arena in the city centre. The O2 Apollo, an Art Deco former cinema where The Beatles once played, and Bridgewater Hall, home of the Hallé Orchestra, cover the mid-size and classical end, while the Frog and Bucket comedy club has been launching UK comedians since 1994. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Birmingham: `Birmingham has a genuine claim as the birthplace of heavy metal — Black Sabbath formed in Aston and played their first gig at a pub on Hill Street in 1968, a heritage the city still marks with its "Home of Metal" mural trail. For live shows today, bp pulse LIVE and Utilita Arena Birmingham handle the biggest touring acts, Symphony Hall (rated among the finest-sounding concert halls in the country) hosts the City of Birmingham Symphony Orchestra, and Birmingham Hippodrome — one of the busiest single theatres in the UK — is home to Birmingham Royal Ballet. The Glee Club, founded here in 1994, was the first dedicated comedy club to open outside London. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Glasgow: `Glasgow was named the UK's first UNESCO City of Music in 2008, reflecting a live scene that's genuinely one of the busiest in the country. The OVO Hydro is one of the world's highest-grossing arenas by ticket sales, while the legendary Barrowland Ballroom — rebuilt in 1960 and famous among touring musicians for its atmosphere — and King Tut's Wah Wah Hut, the tiny venue where Oasis were signed in 1993, cover the smaller end. Glasgow Royal Concert Hall hosts the city's classical and folk programme, including the annual Celtic Connections festival. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Edinburgh: `Edinburgh is home to the largest arts festival in the world — the Edinburgh Festival Fringe, running every August since 1947, now spanning thousands of shows across hundreds of venues. Outside festival season, Murrayfield Stadium hosts the city's biggest stadium concerts, the Edinburgh Playhouse (Scotland's largest theatre) and Usher Hall cover major touring shows and orchestral concerts, and Fringe stalwarts like the Gilded Balloon and Monkey Barrel Comedy keep the city's comedy scene running year-round. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Leeds: `Leeds' live scene runs from First Direct Bank Arena, a fan-shaped 13,000+ capacity venue opened in 2013 and named the world's best new venue at the time, down to the Brudenell Social Club — a converted social club regularly named one of the UK's best small venues, having hosted everyone from Franz Ferdinand to Kaiser Chiefs. The Victorian Leeds Grand Theatre is home to Opera North, while the historic City Varieties Music Hall, dating to 1865, once hosted Houdini and Charlie Chaplin. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Liverpool: `Liverpool's Beatles heritage is the most famous live-music association of any UK city — The Beatles played the Cavern Club close to 300 times between 1961 and 1963, and a rebuilt version of the club still operates on the same street today. For bigger shows, the M&S Bank Arena hosted Eurovision in 2023, while the Liverpool Empire Theatre and Liverpool Philharmonic Hall, home to the Royal Liverpool Philharmonic Orchestra, cover the city's theatre and classical programme. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Bristol: `Bristol is internationally known as the birthplace of trip hop — Massive Attack, Portishead and Tricky all emerged from the city in the late 1980s and early 1990s, a scene closely tied to Bristol's street-art culture and Banksy's own beginnings as a local graffiti artist. Bristol Beacon, the city's historic main hall (formerly Colston Hall), reopened in 2023 after a major refurbishment, while the Bristol Hippodrome and O2 Academy Bristol cover touring theatre and mid-size gigs. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Cardiff: `As Wales' capital, Cardiff is the country's national events hub — home to the Principality Stadium, one of the world's largest stadiums with a retractable roof, which has hosted U2, Beyoncé and Taylor Swift, and to St David's Hall, Wales' National Concert Hall. Utilita Arena Cardiff has hosted Stereophonics and Manic Street Preachers, while Cardiff Castle's grounds have become a major outdoor concert venue each summer. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Belfast: `Belfast's Cathedral Quarter is the heart of the city's live scene, home to the Ulster Hall — a Victorian hall where Led Zeppelin first played "Stairway to Heaven" live in 1971 — and Limelight, the venue where Oasis learned they'd hit UK Number One in 1994. The O2 Belfast (recently rebranded from the SSE Arena) is Northern Ireland's biggest indoor arena, while Waterfront Hall hosts the Ulster Orchestra and the annual Belfast Festival at Queen's. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Nottingham: `Nottingham's Rock City has been named the UK's best venue by Kerrang! ten years running and has hosted everyone from Nirvana to Oasis since it opened in 1980, alongside its sister venue Rescue Rooms next door. Motorpoint Arena Nottingham handles the city's biggest touring shows, the Theatre Royal — dating to 1865 — hosted the world premiere of Agatha Christie's The Mousetrap, and Just the Tonic, part of a respected UK comedy club chain, was founded here. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Newcastle: `Newcastle City Hall has an extraordinary gig history — Bob Dylan, the Rolling Stones, The Who and David Bowie's Ziggy Stardust tour all played there in the 1960s and 70s, and Motörhead recorded most of a classic live album there in 1981. Utilita Arena Newcastle takes the city's biggest shows, NX Newcastle (a converted 1920s cinema and ballroom) has hosted Arctic Monkeys and Adele, and The Stand Comedy Club is part of a well-regarded UK comedy chain. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Leicester: `Leicester's De Montfort Hall, opened in 1913, has hosted Buddy Holly, The Beatles and Bob Dylan across its century of shows. The King Power Stadium has staged major concerts including two sold-out nights from Kasabian, O2 Academy Leicester covers mid-size touring acts, and Curve — a striking theatre opened by the Queen in 2008 — hosts major touring musicals and original productions. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Sheffield: `Sheffield has one of the strongest music heritages of any UK city outside London and Manchester — the "Steel City" electronic scene produced The Human League and Heaven 17, while Pulp and Arctic Monkeys are both Sheffield bands closely identified with the city. Utilita Arena Sheffield sold out instantly for Arctic Monkeys in 2013, Sheffield City Hall has hosted The Beatles and Elton John since 1932, and the Crucible Theatre, best known for the World Snooker Championship, also runs a full drama programme. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Derby: `Derby's live scene centres on Becketwell in the city centre, home to Vaillant Live — a 3,500-capacity venue for concerts, comedy and family shows that opened in 2025 and quickly became the city's biggest draw. For a smaller, gig-going crowd, The Flowerpot and The Hairy Dog are Derby's long-standing live music venues, both a short walk from the centre. Derby Theatre covers drama and touring shows, while just outside the city, Donington Park hosts major motorsport events and festivals including Download. Derby Arena adds a multi-use venue for bigger sporting fixtures. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Coventry: `Coventry is the genuine birthplace of the 2 Tone ska movement — The Specials and The Selecter both formed here, commemorated today at the Coventry Music Museum. The city was also UK City of Culture in 2021. The Coventry Building Society Arena hosts major stadium shows up to 40,000 capacity, while Warwick Arts Centre, the largest arts venue in the Midlands outside London's Barbican, runs a packed year-round programme. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Southampton: `Southampton's Mayflower Theatre has hosted The Beatles, the Rolling Stones and Queen since opening in 1928, and remains the city's biggest indoor venue. The Utilita Bowl (Hampshire's cricket ground) has staged huge outdoor shows including Oasis and Arctic Monkeys, while the O2 Guildhall — bombed during the Southampton Blitz and rebuilt — has hosted the Rolling Stones, The Who and David Bowie. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Portsmouth: `Portsmouth's live scene centres on the Guildhall, a grand civic hall rebuilt after WWII bombing and reopened by the Queen in 1959, and the Portsmouth Pyramids Centre on Southsea seafront. The New Theatre Royal, an intimate Victorian theatre that survived a fire and a near-demolition, and the Wedgewood Rooms — home to the city's longest-running comedy club — cover the smaller end, with past acts including Jo Brand and Michael McIntyre. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Norwich: `Norwich Arts Centre, housed in a converted medieval church, was named NME's Britain's Best Small Venue in 2014 after hosting Nirvana in 1989 and Oasis in 1994 — long before either band was famous. The Waterfront, run by the University of East Anglia's students' union, has a similar track record with Radiohead and Amy Winehouse, while Norwich Theatre Royal, one of England's oldest theatre sites, dates back to 1758. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Brighton: `Brighton Fringe is one of the largest arts festivals in the world, running every spring since the late 1960s across more than 150 venues. Brighton Dome hosted the 1974 Eurovision Song Contest — the night ABBA won with "Waterloo" — and the Brighton Centre has staged everyone from Queen to Wham! since 1977. Komedia, founded in 1994, helped launch the early careers of Sacha Baron Cohen and Graham Norton. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Oxford: `Oxford has a genuine rock pedigree — Radiohead, Supergrass, Ride and Foals all came out of the city, and BPI research for National Album Day named Oxford the UK's top city for producing successful rock artists on a per-capita basis. The New Theatre is Oxford's largest indoor venue, O2 Academy Oxford (co-funded in the 1990s by Radiohead and Supergrass themselves) covers mid-size gigs, and the Sheldonian Theatre, designed by Christopher Wren in the 1660s, still hosts concerts today. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Cambridge: `Cambridge's live scene is built around its university culture, from the intimate ADC Theatre — Britain's oldest university playhouse — to the Cambridge Corn Exchange and Cambridge Junction, which between them cover the city's biggest touring shows and dedicated live music. The Portland Arms, a well-known local pub venue with its own soundproofed gig room, anchors the grassroots scene. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Exeter: `Exeter's live scene runs through the University of Exeter's Great Hall, which has hosted U2, Bob Marley, Blur, Radiohead and Muse since the 1950s, alongside the mid-size Exeter Corn Exchange and the multi-arts Exeter Phoenix. Exeter Cathedral and its grounds also host concerts and events throughout the year. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Plymouth: `Plymouth's live scene centres on Plymouth Arena (formerly Plymouth Pavilions), where Arctic Monkeys' 2006 show sold out in under an hour — a venue record only later matched by Gary Barlow — and the Theatre Royal Plymouth, a major regional theatre complex that runs one of the UK's largest outreach programmes. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Hull: `Hull's live scene was transformed by its year as UK City of Culture in 2017, which brought a refurbished Hull New Theatre and a new arena, Connexin Live. Hull City Hall, designed by the same architect as the London Palladium, has hosted acts from Siouxsie and the Banshees to The Damned, while the tiny New Adelphi Club has hosted early gigs by Oasis, Radiohead, Pulp and The Stone Roses before any of them were famous. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Middlesbrough: `Middlesbrough's Riverside Stadium has hosted major concerts from Take That to Arctic Monkeys, while the Grade II listed Middlesbrough Town Hall — where David Bowie and Iron Maiden both played early in their careers — reopened in 2018 after a major refurbishment. The Middlesbrough Empire, one of only three surviving theatres designed by Edwardian architect Edward Runtz, still operates today as a live venue. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Sunderland: `Sunderland's Stadium of Light has hosted some of the North East's biggest stadium shows, including Beyoncé and Ed Sheeran, while the Edwardian Sunderland Empire Theatre — where The Beatles played on their first national tour — has been extended to host major West End musicals. The new Fire Station venue, part of the city's Music, Arts and Culture Quarter, won a regional architecture award in 2024. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Bradford: `Bradford holds the UK City of Culture title for 2025, and its live scene has been transformed to match — Bradford Live, a newly converted 3,800-capacity venue inside a former 1930s cinema, joins the historic St George's Hall (one of the UK's oldest concert halls still in use) and the Edwardian Alhambra Theatre, home to Opera North and the Royal Shakespeare Company. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Reading: `Reading is home to the UK's longest-running major music festival — Reading Festival has been held on the same Richfield Avenue site since 1971, twinned with Leeds Festival since 1999. Year-round, The Hexagon is the city's civic concert hall and Sub89 covers the smaller touring and club circuit. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  'Milton Keynes': `Milton Keynes punches well above its size for stadium-scale live music — the National Bowl, built into a former clay pit in 1979, hosted three consecutive sold-out nights from Michael Jackson and has staged Queen, Metallica and Muse over the decades, while Stadium MK has hosted Take That and Rammstein. The Stables in Wavendon, founded by jazz musicians John Dankworth and Cleo Laine in 1970, runs around 400 concerts a year. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Bournemouth: `Bournemouth International Centre's Windsor Hall is one of the bigger indoor music venues in England, with a history that includes major political conferences alongside concerts. The Bournemouth Pavilion Theatre, a restored 1929 seafront theatre, and O2 Academy Bournemouth — whose building has hosted touring acts since the Victorian era — cover the rest of the city's live scene. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Ipswich: `Ipswich's live scene runs through the Regent Theatre, East Anglia's largest theatre, and the Ipswich Corn Exchange, which has hosted Blur, Snow Patrol and Muse. Portman Road, Ipswich Town's stadium, has hosted occasional stadium shows including a homecoming concert from Ipswich-born Ed Sheeran, while The Smokehouse anchors the city's grassroots original-music scene. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  'Stoke-on-Trent': `Stoke-on-Trent's live scene centres on Hanley's Cultural Quarter, home to the historic Victoria Hall — where Slash recorded a live album — and the Art Deco Regent Theatre, reopened in 1999 after a £23m renovation attended by the Queen. The Sugarmill, running since 1994, anchors the city's independent and alternative scene, and the bet365 Stadium has hosted stadium shows from Elton John and Bon Jovi. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Wolverhampton: `An Ents24 survey ranked Wolverhampton in the UK's top 10 cities for live music, ahead of Edinburgh, Sheffield and Nottingham — largely down to The Halls Wolverhampton, which reopened in 2023 after a £38m renovation and has hosted The Who, Nirvana and Manic Street Preachers over the decades, and Robin 2, a well-known independent rock and blues venue. The Grand Theatre, dating to 1894, once had Winston Churchill speak from its stage. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Swansea: `Swansea's live scene spans genuine grassroots venues like The Bunkhouse and Sin City up to the Swansea Arena, a 3,500-capacity venue opened in 2022 as part of the Copr Bay regeneration, and the Swansea.com Stadium, which has hosted Elton John, Take That and Arctic Monkeys. Stereophonics, a Swansea band, once played a 55,000-capacity hometown show that's still remembered as one of the biggest gigs in Welsh music history. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,

  Aberdeen: `Aberdeen's live scene is unusually strong for its size — P&J Live, Scotland's largest indoor arena, hosted what's been called the largest indoor concert ever held in Scotland when Gerry Cinnamon sold out its 15,000 capacity in 2019. Two Frank Matcham-designed theatres, His Majesty's Theatre and the Tivoli, plus the Archibald Simpson-designed Music Hall, give the city a strong classical and touring-theatre tradition alongside its modern arena. Whatever the show, TheShowFinder tracks tickets across every major provider so you can compare prices before you buy.`,
}
